name: 'Build & Verify (Windows)'

on: [push, pull_request]

jobs:
  build:
    name: 'Build and run tests'
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      OLM_VERSION: 3.2.8

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Download Olm'
        run: |
          curl -o olm-${OLM_VERSION}.tar.bz2 https://gitlab.matrix.org/matrix-org/olm/-/archive/${OLM_VERSION}/olm-${OLM_VERSION}.tar.bz2
          tar -xjvf olm-${OLM_VERSION}.tar.bz2

      - name: 'Build and install Olm'
        run: |
          cd  olm-${OLM_VERSION}
          cmake -S . -A x64 -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cd ..
          mkdir -p target/classes
          cp olm-${OLM_VERSION}/build/Debug/olm.dll target/classes

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: 'Build and verify'
        run: mvn --batch-mode verify --file pom.xml
