name: 'Build'

on: [push, pull_request]

jobs:
  build:
    name: 'Build and run tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      OLM_VERSION: 3.2.4

    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v2

      - name: 'Install dependencies'
        run: |
          sudo apt update
          sudo apt install cmake

      - name: 'Download Olm'
        run: |
          curl -o olm-${OLM_VERSION}.tar.bz2 https://gitlab.matrix.org/matrix-org/olm/-/archive/${OLM_VERSION}/olm-${OLM_VERSION}.tar.bz2
          tar -xjvf olm-${OLM_VERSION}.tar.bz2

      - name: 'Build and install Olm'
        run: |
          cd  olm-${OLM_VERSION}
          cmake -DCMAKE_INSTALL_PREFIX=/usr . -Bbuild
          cmake --build build
          sudo cmake --install build
          cd ..

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: 'Build and verify'
        run: mvn --batch-mode verify --file pom.xml
